### ISSUE TITLE
why not use fram？

### ISSUE THREAD

**Issue by hualazimo7** [MouseBiteLabs/Game-Boy-MBC3-Multicart#1]
why not replace the sram by fram？like fm18w08？

**Comment by MouseBiteLabs** [comment]
I should add a section for this question.

1) Good new FRAM is expensive ($12+). Cheap FRAM from aliexpress is flaky
(anecdotally, ~50% success rate)
2) SRAM footprint allows you to use SRAM from an original cart.
3) FM18W08 maxes out at only 256K.
4) The Gameboy Color specifically cannot (easily) be made to properly
access the FRAM chip (FM18W08 anyway). FRAM memory access requires
different chip select timing than SRAM, and the Game Boy expects SRAM, so
it is not natively compatible with FRAM carts. You can use an OR gate and
add the CLK on the cart edge to make this timing work, but it only works
(properly) for DMG/MGB/SGB, not the GBC. It usually works in practice for
GBC, but it's technically a datasheet violation and can potentially cause
issues in edge cases. (Thanks to gekkio for pointing this out)

There are proper FRAM chips you can use that work similar to SRAM, but
they're even more expensive and have a completely different footprint.

SRAM + battery lasts for over a decade (even longer if you're not using an
RTC), costs less, and is much more reliable than FRAM. This isn't to throw
shade at any FRAM-based carts, but for me it's more trouble than it's worth.

**Comment by hualazimo7** [comment]
Just a week ago ,  i assembled a pokemon cart using the pcb designed by _'_HDR_‘’_ . With FRAM 'fm18w08-SG' from aliexpress, my pokemon sliver ‘s  save file will be broken  certainly  when i used the cart on different cnsoles. For example, from gbasp  to  gbc.  
It could be the question you just answered.
Maybe i should buy more FRAMS to test or just use your pcb.
Thanks for reply ,thanks for your work.😊

**Comment by hualazimo7** [comment]
Just a week ago ,  i assembled a pokemon cart using the pcb designed by _'_HDR_‘’_ . With FRAM 'fm18w08-SG' from aliexpress, my pokemon sliver ‘s  save file will be broken  certainly  when i used the cart on different cnsoles. For example, from gbasp  to  gbc.  
It could be the question you just answered.
Maybe i should buy more FRAMS to test or just use your pcb.
Thanks for reply ,thanks for your work.😊

**Comment by hualazimo7** [comment]
Just a week ago ,  i assembled a pokemon cart using the pcb designed by _'_HDR_‘’_ . With FRAM 'fm18w08-SG' from aliexpress, my pokemon sliver ‘s  save file will be broken  certainly  when i used the cart on different consoles. For example, from gbasp  to  gbc.  
It could be the question you just answered.
Maybe i should buy more FRAMS to test or just use your pcb.
Thanks for reply ,thanks for your work.😊
